apiVersion: v2
name: protocol-tezos
version: 0.1.0
dependencies:
- name: rarible-helm-chart
  alias: tezos-indexer-api
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: tezos-indexer-listener
  repository: file://../resources/helm/rarible
  version: 0.1.0
