application:
  project: protocol

server:
  shutdown: graceful
  port: 8080

spring:
  application:
    name: protocol-tezos-api
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
  codec:
    max-in-memory-size: 50MB
  aop:
    proxy-target-class: false
  main:
    banner-mode: log
    web-application-type: reactive

rarible:
  core:
    apm:
      agent:
        enabled: true
        server: http://elk_apm-server:8200
        packages: com.rarible.protocol.tezos.api
      web:
        filter:
          enabled: true
      annotation:
        enabled: true

api:
  dipdup:
    host: https://rarible-hangzhounet.dipdup.net/v1/graphql
